- Name: Log @octokit organization statistics
  on:
   workflow_dispatch:

 jobs:
    logOctokitStats:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/org-stats-action@v1.x
        id: stats
        with:
          org: krisha51

      - run: |
          cat << EOF
          result: ${{ steps.stats.outputs.data }}
          EOF
